# Generated by Django 3.0.8 on 2020-07-05 04:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
    ]
