# Generated by Django 3.0.8 on 2020-08-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200705_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('produto',), 'permissions': (('pode_adicionar_produto', 'Pode adicionar produto'),)},
        ),
    ]
