# Generated by Django 3.0.8 on 2020-07-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    initial = True

    dependencies = [
        ('estoque', '0003_estoqueitens_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='atividade',
            field=models.CharField(choices=[('s', 'saida'), ('e', 'entrada')], max_length=1),
        ),
    ]
