# Generated by Django 3.0.8 on 2020-08-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20200705_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoqueitens',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='estoqueitens',
            name='produto',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='EstoqueItens',
        ),
    ]
